# Generated by Django 5.2.4 on 2025-07-30 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_alter_sell_customer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sell",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sells",
                to="base.product",
            ),
        ),
    ]
