# Generated by Django 5.2.4 on 2025-08-01 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_alter_sell_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchase",
            name="vendor",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="base.vendor"
            ),
        ),
    ]
