# Generated by Django 5.2.4 on 2025-08-01 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_alter_purchase_vendor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchase",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="purchases",
                to="base.product",
            ),
        ),
    ]
